name: Ci

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Lint
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.toolchain}}
          components: clippy
      - name: Build
        run: cargo build
      - name: Run clippy
        run: cargo clippy --tests
      - name: Run tests
        run: cargo test

  check-format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - name: rustfmt
        run: cargo fmt --check
      - uses: actionsx/prettier@v3
        with:
          args: --check .
